### ISSUE TITLE
Training on Carla Dataset

### ISSUE THREAD

**Issue by somdats** [cyshih704/DeepLiDAR#3]
@ChingYenShih, Thanks for the simplifies implementation of the DeepLidar,
I have a question
1) The author of the paper uses synthetic dataset "Carla" to train the normal pathway actually using the normals of the simulated dataset, possibly using trainN.py in the original source code, 
Are you directly training on the Kitti dataset after computing normals from the ground truth?

**Comment by cyshih704** [comment]
Yes, I directly train on KITTI dataset after computing normals from the ground truth.
